services:
  mongo:
    image: mongo:7
    container_name: blog_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    networks:
      - blog_net
  mongo-express:
    image: mongo-express:latest
    container_name: blog_mongoexpress
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: "true"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: adminpass
    depends_on:
      - mongo
    networks:
      - blog_net_v2
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog_backend
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb://root:example@mongo:27017/blog_crud?authSource=admin
      JWT_SECRET: your_super_secret_jwt_key_change_this
    depends_on:
      - mongo
    networks:
      - blog_net_v2

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5001/api
    container_name: blog_frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - blog_net_v2

volumes:
  mongo_data:

networks:
  blog_net_v2:
    driver: bridge
